services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://172.17.0.1:5432/jiradb
      - ATL_JDBC_USER=postgres
      - ATL_JDBC_PASSWORD=admin
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
    depends_on:
      - db
    volumes:
      - jira_home:/var/atlassian/jira
      - ./customLib:/opt/atlassian/jira/lib

  db:
    image: postgres:latest
    restart: always
    shm_size: 1gb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: jiradb

volumes:
  jira_home:
